
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Database Configuration
*/}}

{{/*
Renders the database secret name
*/}}
{{- define "airbyte-keycloak.database.secretName" }}
{{- if .Values.database.secretName }}
    {{- .Values.database.secretName }}
{{- else }}
    {{- .Values.secretName | default (printf "%s-airbyte-keycloak-secrets" .Release.Name) }}
{{- end }}
{{- end }}

{{/*
Renders the database.name value
*/}}
{{- define "airbyte-keycloak.database.name" }}
    {{- .Values.database.name | default "keycloak" }}
{{- end }}

{{/*
Renders the database.name environment variable
*/}}
{{- define "airbyte-keycloak.database.name.env" }}
- name: KEYCLOAK_DATABASE_NAME
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-keycloak-env
      key: KEYCLOAK_DATABASE_NAME
{{- end }}

{{/*
Renders the database.host value
*/}}
{{- define "airbyte-keycloak.database.host" }}
    {{- .Values.database.host | default (printf "keycloak-db-svc.%s.svc.cluster.local" .Release.Namespace) }}
{{- end }}

{{/*
Renders the database.host environment variable
*/}}
{{- define "airbyte-keycloak.database.host.env" }}
- name: KEYCLOAK_DATABASE_HOST
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-keycloak-env
      key: KEYCLOAK_DATABASE_HOST
{{- end }}

{{/*
Renders the database.port value
*/}}
{{- define "airbyte-keycloak.database.port" }}
    {{- .Values.database.port | default 5432 }}
{{- end }}

{{/*
Renders the database.port environment variable
*/}}
{{- define "airbyte-keycloak.database.port.env" }}
- name: KEYCLOAK_DATABASE_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-keycloak-env
      key: KEYCLOAK_DATABASE_PORT
{{- end }}

{{/*
Renders the database.user value
*/}}
{{- define "airbyte-keycloak.database.user" }}
    {{- .Values.database.user | default "airbyte" }}
{{- end }}

{{/*
Renders the database.user secret key
*/}}
{{- define "airbyte-keycloak.database.user.secretKey" }}
	{{- .Values.database.userSecretKey | default "KEYCLOAK_DATABASE_USERNAME" }}
{{- end }}

{{/*
Renders the database.user environment variable
*/}}
{{- define "airbyte-keycloak.database.user.env" }}
- name: KEYCLOAK_DATABASE_USERNAME
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-keycloak.database.secretName" . }}
      key: {{ include "airbyte-keycloak.database.user.secretKey" . }}
{{- end }}

{{/*
Renders the database.password value
*/}}
{{- define "airbyte-keycloak.database.password" }}
    {{- .Values.database.password | default "airbyte" }}
{{- end }}

{{/*
Renders the database.password secret key
*/}}
{{- define "airbyte-keycloak.database.password.secretKey" }}
	{{- .Values.database.passwordSecretKey | default "KEYCLOAK_DATABASE_PASSWORD" }}
{{- end }}

{{/*
Renders the database.password environment variable
*/}}
{{- define "airbyte-keycloak.database.password.env" }}
- name: KEYCLOAK_DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ include "airbyte-keycloak.database.secretName" . }}
      key: {{ include "airbyte-keycloak.database.password.secretKey" . }}
{{- end }}

{{/*
Renders the database.url value
*/}}
{{- define "airbyte-keycloak.database.url" }}
    {{- (printf "jdbc:postgresql://%s:%d/%s?currentSchema=%s" (include "airbyte-keycloak.database.host" .) (int (include "airbyte-keycloak.database.port" .)) (include "airbyte-keycloak.database.name" .) (include "airbyte-keycloak.database.schema" .)) }}
{{- end }}

{{/*
Renders the database.url environment variable
*/}}
{{- define "airbyte-keycloak.database.url.env" }}
- name: KEYCLOAK_DATABASE_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-keycloak-env
      key: KEYCLOAK_DATABASE_URL
{{- end }}

{{/*
Renders the database.schema value
*/}}
{{- define "airbyte-keycloak.database.schema" }}
    {{- .Values.database.schema | default "keycloak" }}
{{- end }}

{{/*
Renders the database.schema environment variable
*/}}
{{- define "airbyte-keycloak.database.schema.env" }}
- name: KEYCLOAK_DATABASE_SCHEMA
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-keycloak-env
      key: KEYCLOAK_DATABASE_SCHEMA
{{- end }}

{{/*
Renders the set of all database environment variables
*/}}
{{- define "airbyte-keycloak.database.envs" }}
{{- include "airbyte-keycloak.database.name.env" . }}
{{- include "airbyte-keycloak.database.host.env" . }}
{{- include "airbyte-keycloak.database.port.env" . }}
{{- include "airbyte-keycloak.database.user.env" . }}
{{- include "airbyte-keycloak.database.password.env" . }}
{{- include "airbyte-keycloak.database.url.env" . }}
{{- include "airbyte-keycloak.database.schema.env" . }}
{{- end }}

{{/*
Renders the set of all database config map variables
*/}}
{{- define "airbyte-keycloak.database.configVars" }}
KEYCLOAK_DATABASE_NAME: {{ include "airbyte-keycloak.database.name" . | quote }}
KEYCLOAK_DATABASE_HOST: {{ include "airbyte-keycloak.database.host" . | quote }}
KEYCLOAK_DATABASE_PORT: {{ include "airbyte-keycloak.database.port" . | quote }}
KEYCLOAK_DATABASE_URL: {{ include "airbyte-keycloak.database.url" . | quote }}
KEYCLOAK_DATABASE_SCHEMA: {{ include "airbyte-keycloak.database.schema" . | quote }}
{{- end }}

{{/*
Renders the set of all database secret variables
*/}}
{{- define "airbyte-keycloak.database.secrets" }}
KEYCLOAK_DATABASE_USERNAME: {{ include "airbyte-keycloak.database.user" . | quote }}
KEYCLOAK_DATABASE_PASSWORD: {{ include "airbyte-keycloak.database.password" . | quote }}
{{- end }}
