
{{/* DO NOT EDIT: This file was autogenerated. */}}

{{/*
    Keycloak Configuration
*/}}

{{/*
Renders the keycloak.url value
*/}}
{{- define "airbyte-keycloak.keycloak.url" }}
    {{- .Values.keycloak.url }}
{{- end }}

{{/*
Renders the keycloak.url environment variable
*/}}
{{- define "airbyte-keycloak.keycloak.url.env" }}
- name: KEYCLOAK_HOSTNAME_URL
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-keycloak-env
      key: KEYCLOAK_HOSTNAME_URL
{{- end }}

{{/*
Renders the keycloak.port value
*/}}
{{- define "airbyte-keycloak.keycloak.port" }}
    {{- .Values.keycloak.port | default 8180 }}
{{- end }}

{{/*
Renders the keycloak.port environment variable
*/}}
{{- define "airbyte-keycloak.keycloak.port.env" }}
- name: KEYCLOAK_PORT
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-keycloak-env
      key: KEYCLOAK_PORT
{{- end }}

{{/*
Renders the keycloak.javaOpts value
*/}}
{{- define "airbyte-keycloak.keycloak.javaOpts" }}
    {{- (printf "-Djgroups.dns.query=%s-airbyte-keycloak-headless-svc" .Release.Name) }}
{{- end }}

{{/*
Renders the keycloak.javaOpts environment variable
*/}}
{{- define "airbyte-keycloak.keycloak.javaOpts.env" }}
- name: JAVA_OPTS_APPEND
  valueFrom:
    configMapKeyRef:
      name: {{ .Release.Name }}-airbyte-keycloak-env
      key: JAVA_OPTS_APPEND
{{- end }}

{{/*
Renders the set of all keycloak environment variables
*/}}
{{- define "airbyte-keycloak.keycloak.envs" }}
{{- include "airbyte-keycloak.keycloak.url.env" . }}
{{- include "airbyte-keycloak.keycloak.port.env" . }}
{{- include "airbyte-keycloak.keycloak.javaOpts.env" . }}
{{- end }}

{{/*
Renders the set of all keycloak config map variables
*/}}
{{- define "airbyte-keycloak.keycloak.configVars" }}
KEYCLOAK_HOSTNAME_URL: {{ include "airbyte-keycloak.keycloak.url" . | quote }}
KEYCLOAK_PORT: {{ include "airbyte-keycloak.keycloak.port" . | quote }}
JAVA_OPTS_APPEND: {{ include "airbyte-keycloak.keycloak.javaOpts" . | quote }}
{{- end }}
