apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-airbyte-keycloak-env
  labels:
    {{- include "airbyte-keycloak.labels" . | nindent 4 }}
data:
  {{- include "airbyte-keycloak.database.configVars" . | nindent 2 }}
  {{- include "airbyte-keycloak.keycloak.configVars" . | nindent 2 }}
  {{- include "airbyte-keycloak.postgres.configVars" . | nindent 2 }}
