apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-secrets
  labels:
    {{- include "airbyte-keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "airbyte-keycloak.admin.secrets" . | nindent 2 }}
  {{- include "airbyte-keycloak.database.secrets" . | nindent 2 }}
  {{- include "airbyte-keycloak.postgres.secrets" . | nindent 2 }}
